# Generated by Django 5.2.2 on 2025-06-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'group category',
                'verbose_name_plural': 'group categories',
                'db_table': 'group categories',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('monthly_payment', models.IntegerField(verbose_name='monthly_payment')),
                ('phone_number_or_email', models.CharField(max_length=256, verbose_name='phone_or_email')),
                ('debt', models.IntegerField(verbose_name='debt')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256, verbose_name='group_name')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.groupcategory')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='common.teacher')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'group',
                'db_table': 'groups',
            },
        ),
    ]
