# Generated by Django 5.2.2 on 2025-06-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(choices=[('Du Chor Ju', 'Dushanba Chorshanba Juma'), ('Se Pay Shan', 'Seshanba Payshanba Shanba')], default='', verbose_name='days'),
            preserve_default=False,
        ),
    ]
