# Generated by Django 5.2.2 on 2025-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_student_age_remove_teacher_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='debt',
        ),
        migrations.AddField(
            model_name='student',
            name='joined',
            field=models.DateField(auto_now=True, verbose_name='joined'),
        ),
    ]
