# Generated by Django 5.2.2 on 2025-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_student_debt_student_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='balance'),
        ),
    ]
