# Generated by Django 5.2.2 on 2025-06-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_student_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monthly_payment',
            field=models.IntegerField(verbose_name='monthly payment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number_or_email',
            field=models.CharField(max_length=256, verbose_name='phone or email'),
        ),
    ]
