# Generated by Django 5.2.2 on 2025-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_or_email',
            field=models.CharField(default='', max_length=256, verbose_name='phone_or_email'),
            preserve_default=False,
        ),
    ]
