# Generated by Django 5.2.2 on 2025-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_group_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='time'),
        ),
    ]
