# Generated by Django 5.2.2 on 2025-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_group_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
    ]
