# Generated by Django 5.2.2 on 2025-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_alter_group_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='slug'),
        ),
    ]
