# Generated by Django 5.2.2 on 2025-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_group_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_started',
            field=models.DateField(auto_now=True, verbose_name='date started'),
        ),
    ]
