# Generated by Django 5.2.2 on 2025-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_group_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
