# Generated by Django 5.2.2 on 2025-06-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_group_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_started',
            field=models.DateField(null=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='group',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, verbose_name='duration months'),
        ),
    ]
