# Generated by Django 5.2.2 on 2025-06-15 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_group_date_started_alter_group_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_or_email',
            field=models.CharField(max_length=256, verbose_name='phone or email'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='common.student')),
            ],
        ),
    ]
