# Generated by Django 5.2.2 on 2025-06-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_teacher_birth_date_alter_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
